from selenium.webdriver.common.by import By

class GlobexLocators():
    custom_data_select = (By.NAME, "customer")
    custom_vip_input = (By.ID, "vip")
    custom_customer_name = (By.ID, "customerName")
    custom_data_button = (By.ID, "customer-set")
    bank_list_frame = (By.ID, "paywithmybank-iframe-widget-container")
    bank_list_button = (By.ID, "wdt-bankTiles-openAllBanks")
    select_bank_frame = (By.ID, "paywithmybank-iframe")
    bank_name_input = (By.ID, "lbx-listBank-inputSearch")
    #selected_bank_div = (By.ID, 'lbx-listBank-select200005501')
    selected_bank_div = (By.XPATH, '/html/body/div/div/div[1]/div/div[1]/div[2]/div[2]/div[1]/div/div[1]/div')
    bank_data_frame = (By.ID, "paywithmybank-iframe")
    popup_frame = (By.ID, "slider-button")
    login_frame = (By.ID, "lbx-iframeAuthenticate")
    username_input = (By.ID, "lbx-formAuthenticate-authFields-inputusername")
    password_input = (By.ID, "lbx-formAuthenticate-authFields-inputpassword")
    root_frame = (By.XPATH, '//*[@id="root"]')
    account_frame = (By.XPATH, '//*[@id="paywithmybank-iframe"]')
    account_iframe = (By.ID, 'paywithmybank-iframe')
    submit_buttom = (By.ID, "lbx-accountList-submit")
